/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/lvl.glb -o src/components/levels.jsx -r public -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ inputRotationZ = 0, ...props }) {
  const { nodes, materials } = useGLTF('/model/lvl.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="input" geometry={nodes.input.geometry} material={materials.material_0} position={[-0.056, 0.151, 0.376]} rotation={[Math.PI / 2, 0, 0.032]} />
      <mesh name="input001" geometry={nodes.input001.geometry} material={materials.material_0} position={[0.001, 0.315, -0.063]}  rotation={[Math.PI / 2, 0, 0.032 + inputRotationZ]}  />
    </group>
  )
}

useGLTF.preload('/model/lvl.glb')
