/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/PPtruck.glb -o src/components/Truck.jsx -r public -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"

export function ModelTruck(props) {
     const { nodes, materials } = useGLTF('/model/TruckA.glb')

     const wheelRef1 = useRef()
     const wheelRef2 = useRef()
     const wheelRef3 = useRef()
     const wheelRef4 = useRef()

     // Цикл анимации вращения колес по оси X
     useFrame((state, delta) => {
          const rotationSpeed = 2 * delta

          if (wheelRef1.current) wheelRef1.current.rotation.x += rotationSpeed
          if (wheelRef2.current) wheelRef2.current.rotation.x += rotationSpeed
          if (wheelRef3.current) wheelRef3.current.rotation.x += rotationSpeed
          if (wheelRef4.current) wheelRef4.current.rotation.x += rotationSpeed
     })

     return (
          <group {...props} dispose={null} scale={15} position={[0, 2.9, 0]} rotation={[0, 1, 0]} >

               {/* КУЗОВ И КАРКАС МАШИНЫ */}
               <mesh name="texture_mapping001" geometry={nodes.texture_mapping001.geometry}>
                    <meshBasicMaterial map={materials.material_0?.map} color={materials.material_0?.color} side={2} />
               </mesh>
               <mesh name="texture_mapping002" geometry={nodes.texture_mapping002.geometry}>
                    <meshBasicMaterial map={materials['material_0.001']?.map} color={materials['material_0.001']?.color} side={2} />
               </mesh>

               {/* КОЛЕСО 1 */}
               <group ref={wheelRef1} name="Object021_Material_#276_0002" position={[-0.119, -0.138, -0.307]}>
                    <mesh name="Object021_Material_#276_0002_1" geometry={nodes['Object021_Material_#276_0002_1'].geometry}>
                         <meshBasicMaterial map={materials['Material_276.002']?.map} color={materials['Material_276.002']?.color} side={2} />
                    </mesh>
                    <mesh name="Object021_Material_#276_0002_2" geometry={nodes['Object021_Material_#276_0002_2'].geometry}>
                         <meshBasicMaterial map={materials['Material_338.002']?.map} color="#666666" side={2} toneMapped={false} />
                    </mesh>
                    <mesh name="Object021_Material_#276_0002_3" geometry={nodes['Object021_Material_#276_0002_3'].geometry}>
                         <meshBasicMaterial map={materials['Material_291.002']?.map} color={materials['Material_291.002']?.color} side={2} />
                    </mesh>
               </group>

               {/* КОЛЕСО 2 */}
               <group ref={wheelRef2} name="Object021_Material_#276_0004" position={[-0.121, -0.143, -0.206]} rotation={[-1.246, 0, 0]}>
                    <mesh name="Object021_Material_#276_0004_1" geometry={nodes['Object021_Material_#276_0004_1'].geometry}>
                         <meshBasicMaterial map={materials['Material_276.004']?.map} color={materials['Material_276.004']?.color} side={2} />
                    </mesh>
                    <mesh name="Object021_Material_#276_0004_2" geometry={nodes['Object021_Material_#276_0004_2'].geometry}>
                         <meshBasicMaterial map={materials['Material_338.004']?.map} color="#666666" side={2} toneMapped={false} />
                    </mesh>
                    <mesh name="Object021_Material_#276_0004_3" geometry={nodes['Object021_Material_#276_0004_3'].geometry}>
                         <meshBasicMaterial map={materials['Material_291.004']?.map} color={materials['Material_291.004']?.color} side={2} />
                    </mesh>
               </group>

               {/* КОЛЕСО 3 */}
               <group ref={wheelRef3} name="Object021_Material_#276_0005" position={[-0.115, -0.143, 0.165]}>
                    <mesh name="Object021_Material_#276_0006" geometry={nodes['Object021_Material_#276_0006'].geometry}>
                         <meshBasicMaterial map={materials['Material_276.006']?.map} color={materials['Material_276.006']?.color} side={2} />
                    </mesh>
                    <mesh name="Object021_Material_#276_0006_1" geometry={nodes['Object021_Material_#276_0006_1'].geometry}>
                         <meshBasicMaterial map={materials['Material_338.006']?.map} color="#666666" side={2} toneMapped={false} />
                    </mesh>
                    <mesh name="Object021_Material_#276_0006_2" geometry={nodes['Object021_Material_#276_0006_2'].geometry}>
                         <meshBasicMaterial map={materials['Material_291.006']?.map} color={materials['Material_291.006']?.color} side={2} />
                    </mesh>
               </group>

               {/* КОЛЕСО 4 */}
               <group ref={wheelRef4} name="Object021_Material_#276_0001" position={[-0.126, -0.142, 0.376]} rotation={[-2.411, 0, 0]}>
                    <mesh name="Object021_Material_#276_0007" geometry={nodes['Object021_Material_#276_0007'].geometry}>
                         <meshBasicMaterial map={materials['Material_276.007']?.map} color={materials['Material_276.007']?.color} side={2} />
                    </mesh>
                    <mesh name="Object021_Material_#276_0007_1" geometry={nodes['Object021_Material_#276_0007_1'].geometry}>
                         <meshBasicMaterial map={materials['Material_338.002']?.map} color="#666666" side={2} toneMapped={false} />
                    </mesh>
                    <mesh name="Object021_Material_#276_0007_2" geometry={nodes['Object021_Material_#276_0007_2'].geometry}>
                         <meshBasicMaterial map={materials['Material_291.007']?.map} color={materials['Material_291.007']?.color} side={2} />
                    </mesh>
               </group>

          </group>
     )
}

// useGLTF.preload('/model/TruckA.glb')
