/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/PPtruck.glb -o src/components/Truck.jsx -r public -k 
*/

import React, { useEffect, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"

// Описание материалов данными: [ключ в materials, цвет-переопределение, toneMapped]
// Одинаковые комбинации карта+цвет переиспользуют один материал, а не создают копии
const BODY_PARTS = [
     { node: 'texture_mapping001', material: 'material_0' },
     { node: 'texture_mapping002', material: 'material_0.001' },
]

const WHEELS = [
     {
          name: 'Object021_Material_#276_0002',
          position: [-0.119, -0.138, -0.307],
          rotation: [0, 0, 0],
          parts: [
               { node: 'Object021_Material_#276_0002_1', material: 'Material_276.002' },
               { node: 'Object021_Material_#276_0002_2', material: 'Material_338.002', color: '#666666', toneMapped: false },
               { node: 'Object021_Material_#276_0002_3', material: 'Material_291.002' },
          ],
     },
     {
          name: 'Object021_Material_#276_0004',
          position: [-0.121, -0.143, -0.206],
          rotation: [-1.246, 0, 0],
          parts: [
               { node: 'Object021_Material_#276_0004_1', material: 'Material_276.004' },
               { node: 'Object021_Material_#276_0004_2', material: 'Material_338.004', color: '#666666', toneMapped: false },
               { node: 'Object021_Material_#276_0004_3', material: 'Material_291.004' },
          ],
     },
     {
          name: 'Object021_Material_#276_0005',
          position: [-0.115, -0.143, 0.165],
          rotation: [0, 0, 0],
          parts: [
               { node: 'Object021_Material_#276_0006', material: 'Material_276.006' },
               { node: 'Object021_Material_#276_0006_1', material: 'Material_338.006', color: '#666666', toneMapped: false },
               { node: 'Object021_Material_#276_0006_2', material: 'Material_291.006' },
          ],
     },
     {
          name: 'Object021_Material_#276_0001',
          position: [-0.126, -0.142, 0.376],
          rotation: [-2.411, 0, 0],
          parts: [
               { node: 'Object021_Material_#276_0007', material: 'Material_276.007' },
               { node: 'Object021_Material_#276_0007_1', material: 'Material_338.002', color: '#666666', toneMapped: false },
               { node: 'Object021_Material_#276_0007_2', material: 'Material_291.007' },
          ],
     },
]

export function ModelTruck(props) {
     const { nodes, materials } = useGLTF('/model/TruckA.glb')

     // Материалы создаются один раз на загруженную модель.
     // Дубликаты (одна и та же текстура + цвет) переиспользуются
     const basicMaterials = useMemo(() => {
          const cache = new Map()
          const created = []

          const get = ({ material, color, toneMapped }) => {
               const source = materials[material]
               const map = source?.map ?? null
               const key = `${map ? map.uuid : 'none'}|${color ?? source?.color?.getHexString() ?? 'default'}|${toneMapped ?? true}`

               let mat = cache.get(key)
               if (!mat) {
                    const params = { map, side: THREE.DoubleSide }
                    // Цвет-переопределение имеет приоритет, иначе берём оригинальный из модели
                    if (color) params.color = color
                    else if (source?.color) params.color = source.color
                    if (toneMapped === false) params.toneMapped = false

                    mat = new THREE.MeshBasicMaterial(params)
                    cache.set(key, mat)
                    created.push(mat)
               }
               return mat
          }

          return {
               body: BODY_PARTS.map(get),
               wheels: WHEELS.map((wheel) => wheel.parts.map(get)),
               created,
          }
     }, [materials])

     // Освобождаем созданные материалы при размонтировании.
     // Геометрии и текстуры принадлежат кешу useGLTF — их не трогаем
     useEffect(() => {
          const { created } = basicMaterials
          return () => created.forEach((mat) => mat.dispose())
     }, [basicMaterials])

     const wheelRefs = useRef([])

     // Один цикл на все колёса вместо четырёх отдельных проверок
     useFrame((state, delta) => {
          const rotationSpeed = 2 * delta
          const wheels = wheelRefs.current

          for (let i = 0; i < wheels.length; i++) {
               const wheel = wheels[i]
               if (wheel) wheel.rotation.x += rotationSpeed
          }
     })

     return (
          <group {...props} dispose={null} scale={15} position={[0, 2.9, 0]} rotation={[0, 1, 0]} >

               {/* КУЗОВ И КАРКАС МАШИНЫ */}
               {BODY_PARTS.map((part, i) => (
                    <mesh
                         key={part.node}
                         name={part.node}
                         geometry={nodes[part.node].geometry}
                         material={basicMaterials.body[i]}
                    />
               ))}

               {/* КОЛЁСА */}
               {WHEELS.map((wheel, wheelIndex) => (
                    <group
                         key={wheel.name}
                         ref={(el) => { wheelRefs.current[wheelIndex] = el }}
                         name={wheel.name}
                         position={wheel.position}
                         rotation={wheel.rotation}
                    >
                         {wheel.parts.map((part, partIndex) => (
                              <mesh
                                   key={part.node}
                                   name={part.node}
                                   geometry={nodes[part.node].geometry}
                                   material={basicMaterials.wheels[wheelIndex][partIndex]}
                              />
                         ))}
                    </group>
               ))}

          </group>
     )
}

// useGLTF.preload('/model/TruckA.glb')
